travis:
  secure:
    BINSTAR_TOKEN: NqgTiygMaAZwfGE7YSb1b8bhsd4xTgUGY8IxLP2IZosIZg9qTnXwQ+Bm2M0o+UxjIdJ4qOtUy4XpCOvvnRCU0SvMNgj/E66Alany4VFLWNkSszXOxrcxGZd3n/9IIvDuml3KNk2nn63AwBlDreqF6KMLjseyfZ2FVvkXNrA9/MtSMpYYymFTvFDCfB2kY17YHlltkCPie9tHLuaZD7WqRpscAUnKt2OJ3obdg0FAatsYfGyb7G88y8FGqQXU0yYCvilBJPra5RY7ba5UVxq9BF8JdYJGUXtnef38UHqIqH2tAjQgad5DLHybetNru3il0ztZ7C3gUn5jTH/R4cfbZoeOyuDUZgoZQlDEKaUdXx/WM6LnAqODkt3H1RnJUKTxW2WtLPPCZ76dtVpQLdDyskKF6XAKkC2Q0OR/4tRsNtCf+SP0p/wvsIVOLtFX5eFvq9DUuYPf+uvFLqUZ0m6qJz/hXMayI63Vb9tQ5VPX1DXmai3ms3c72WsQ6H8C89+y3rHgZlIk3WLF0ub9G+9aARVfqTY2aQ2mhroDzfagvl4WwAeaW0GUeZ3hporbOv+e0ZkaWl8WC/WiFCch08ORgnQwBhYVgX9p14xE1ocZJ6lhKK5CRIjEuTsRq/lvdPYVxiBJWqPIMke+QJK8+NcSHv6R+3j8wYD+EVsX4taVlPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
